### ISSUE TITLE
Crashed while 'saving record'

### ISSUE THREAD

**Issue by Lagrand** [liu-yun/wisdomtree#2]
I'm having a problem while running wisdomtree. Maybe it's a bug?

Environment: bash on ubuntu on windows, fresh install. Just followed the instructions listed in readme.
Details:
```
Traceback (most recent call last):
  File "./study.py", line 95, in <module>
    save_record(section, lesson['chapterId'], lesson['id'])
  File "./study.py", line 86, in save_record
    logger.info(dic['name'] + r.json()['studyPercenter'])
  File "/usr/lib/python3/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
```
Thanks in advance.

**Comment by liu-yun** [comment]
Currently I don't have any courses to test. You can send me your `userinfo.py` (no phone or password needed).

**Comment by liu-yun** [comment]
The API has changed a lot. I will try to update this script in the following days.
