### ISSUE TITLE
What's this?After I login and press y,it return this.

### ISSUE THREAD

**Issue by Sakakibara-Hu** [liu-yun/wisdomtree#3]
Traceback (most recent call last):
  File "study.py", line 100, in <module>
    save_record(lesson, None, None)
  File "study.py", line 89, in save_record
    logger.info(dic['name'] + r.json()['studyPercenter'])
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Sakakibara-Hu** [comment]
Please help! I have not found the answer of my class test........how awful

**Comment by liu-yun** [comment]
See #2
